name: Druid

permalink: /blog/:year/:month/:day/:title.html
markdown: redcarpet

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "with_toc_data"]

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - scss
  - css-extra
  - private
  - _staging
  - release.sh

highlighter: pygments

title: 'Druid'
description: 'RealÂ²time Exploratory Analytics on Large Datasets'


druid_versions:
  - release: 25.0
    versions:
      - version: 25.0.0
        date: 2023-01-04
  - release: 24.0.2
    versions:
      - version: 24.0.2
        date: 2022-12-21
  - release: 24.0.1
    versions:
      - version: 24.0.1
        date: 2022-11-21

tranquility_stable_version: 0.8.3

gems:
  - jekyll-textile-converter

prose:
  metadata:
    siteurl: 'https://druid.apache.org'

    _posts:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: ""
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"

